
name: PlayWithCI

on:
  push:
    branches: 
    - main

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
    -   name: Run testing
        run: echo "Run testing"

    -   name: Git clone repo
        uses: actions/checkout@v1
    -   name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
   
  Deploy:
     runs-on: ubuntu-latest 
     needs: [Testing]
     steps:
     -  name: Run deploy
        run: echo "Run deploy"
