
name: Node.js CI

on:
  push:
    branches: 
    - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    -   name: Print Message 1
        run: echo "Run testing"

    -   name: Git clone repo
        uses: actions/checkout@v1 
   
  deploy_test:
     runs-on: ubuntu-latest 
     needs: [testing]
     steps:
     -  name: Print Message 2
        run: echo "Run deploy"
     -  name: Check Mocha
        run: mocha --version
