
name: Node.js CI

on:
  push:
    branches: 
    	- main
	
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    -   name: Print Message 1
        run: echo "Run testing"
   
  deploy_test:
     runs-on: ubuntu-latest 
   
     steps:
     -  name: Print Message 2
        run: echo "Run deploy"
